filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*]

before_commands:
    - "composer install --prefer-source"

tools:
    external_code_coverage: true
    php_code_coverage: true
    php_analyzer: true
    php_mess_detector: true
    php_code_sniffer: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
    sensiolabs_security_checker: true
